/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see .gitlab-ci.yaml).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'local'

// Config for firebase
export const firebase = {
  apiKey: "AIzaSyCQW4pAizLUdYi8_gpuByR26Yaae1NNoMY",
  authDomain: "hibuy-70f93.firebaseapp.com",
  databaseURL: "https://hibuy-70f93.firebaseio.com",
  projectId: "hibuy-70f93",
  storageBucket: "hibuy-70f93.appspot.com",
  messagingSenderId: "358065499039",
  appId: "1:358065499039:web:1d640602d59ce28463ebaa",
  measurementId: "G-Q14CXG49C5"
}

// Config to override default reduxFirebase config in store/createStore
// which is not environment specific.
// For more details, visit http://react-redux-firebase.com/docs/api/enhancer.html
export const reduxFirebase = {
  userProfile: 'users',
  enableLogging: false, // enable/disable Firebase Database Logging
  useFirestoreForProfile: true,
  enableRedirectHandling: false,
  resetBeforeLogin: true
}

export default {
  env,
  firebase,
  reduxFirebase
}
